out_dir: results/gpp
metric_best: log_10_mse
metric_agg: argmin
wandb:
  use: False
  project: graph-prop-pred
dataset:
  format: custom
  name: graph-prop-pred_sssp
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  edge_encoder: False
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_best: True
  ckpt_clean: True
model:
  type: gnn_xlstm
  loss_fun: mse
gnn:
  head: inductive_node
  dim_inner: 10 # Careful - you can't make this too small or it'll start causing problems with the size of the PE embeddings
  layers_mp: 10
  layers_post_mp: 1
  batchnorm: False
  act: tanh
  shared: False
  use_k_hop_aggregation: True
xlstm:
  num_blocks: 1
  num_heads: 1
  memory_dim: 16
  aggr: add
  input_norm_type: none # careful - this cannot be group
  hidden_norm_type: group
  input_gate_type: ego
  dropout: None
optim:
  optimizer: adam
  weight_decay: 0.000001
  base_lr: 0.003
  max_epoch: 1500
  scheduler: None
  early_stopping_patience: 100