out_dir: results/key_recall_regression
metric_best: mse
metric_agg: argmin
wandb:
  use: False
  project: key-recall
dataset:
  format: custom
  name: key-recall-regression
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  edge_encoder: False
  node_encoder_bn: False
key_recall:
  num_key_nodes: 8
  value_dimension: 16
  num_train_graphs: 8000
  num_val_graphs: 1000
  num_test_graphs: 1000
train:
  mode: custom
  batch_size: 64
  eval_period: 1
  ckpt_best: True
  ckpt_clean: True
model:
  type: gnn_xlstm
  loss_fun: mse
  graph_pooling: add
gnn:
  head: ring-transfer
  dim_inner: 32
  layers_mp: 2
  layers_post_mp: 1
  batchnorm: False
  act: none
  shared: False
  use_k_hop_aggregation: False
xlstm:
  num_blocks: 1
  num_heads: 1
  memory_dim: 16
  v_memory_dim: 16
  aggr: add
  input_norm_type: none # careful - this cannot be group
  hidden_norm_type: group
  input_gate_type: ego
  dropout: None
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 200
  early_stopping_loss_threshold: 0.001
  early_stopping_patience: 50