out_dir: results/ring_transfer
metric_best: accuracy
wandb:
  use: False
  project: ring-transfer
dataset:
  format: custom
  name: ring-transfer
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  edge_encoder: False
train:
  mode: custom
  batch_size: 16
  eval_period: 1
  ckpt_best: True
  ckpt_clean: True
model:
  type: gnn_ssm
  loss_fun: cross_entropy
  graph_pooling: add
gnn:
  head: ring-transfer
  dim_inner: 64
  layers_mp: 40
  layers_post_mp: 1
  batchnorm: False
  shared: False
  use_k_hop_aggregation: True
ssm:
  message_passing_activation_function: relu
  use_state_matrix: True
  use_input_matrix: True
  state_gating: False
  input_gating: False
  shared_state: True
  shared_input: True
  dyn: True
  state_eigenvalue_magnitude: 1.0
  input_eigenvalue_magnitude: None
  train_state: False
  train_input: False
  conv_func: GCN
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.0005
  min_lr: 1e-5
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
  early_stopping_loss_threshold: 0.001
  early_stopping_patience: 60